// ─── Mock AI Risk Generation Service ──────────────────────────────────────────
// Simulates an AI backend with department-specific risk personas.
// Returns 6-8 bilingual risks per department.

const riskTemplates = {
  IT: [
    { riskName: { ar: 'وصول غير مصرّح للأنظمة الحرجة', en: 'Unauthorized Access to Critical Systems' }, description: { ar: 'العمليات اليومية تتضمن وصول لخوادم الإنتاج وقواعد البيانات، مما يخلق خطر وصول غير مصرح أو تصعيد صلاحيات قد يؤدي لاختراق البيانات.', en: 'Employee daily operations involve access to production servers and databases, creating risk of unauthorized access or privilege escalation that could lead to data breaches.' }, likelihood: 4, impact: 5, riskType: 'Cybersecurity', mitigation: { ar: 'تطبيق مصادقة متعددة العوامل وسياسة الحد الأدنى من الصلاحيات', en: 'Implement MFA and least-privilege access policies' }, confidence: 0.92 },
    { riskName: { ar: 'فقدان البيانات من إجراءات نسخ احتياطي غير سليمة', en: 'Data Loss from Improper Backup Procedures' }, description: { ar: 'التعامل المنتظم مع البيانات دون عمليات تحقق كافية من النسخ الاحتياطية قد يؤدي لفقد غير قابل للاسترداد عند فشل الأنظمة.', en: 'Regular data handling without adequate backup verification may result in irreversible data loss during system failures.' }, likelihood: 3, impact: 4, riskType: 'Operational', mitigation: { ar: 'وضع جدول نسخ احتياطي آلي مع اختبارات استعادة دورية', en: 'Establish automated backup schedules with periodic recovery testing' }, confidence: 0.88 },
    { riskName: { ar: 'تقنية الظل والبرمجيات غير المعتمدة', en: 'Shadow IT and Unapproved Software Usage' }, description: { ar: 'الاعتماد اليومي على أدوات طرف ثالث تتجاوز حوكمة تقنية المعلومات يخلق ثغرات أمنية وفجوات امتثال.', en: 'Daily workflow dependencies on third-party tools that bypass IT governance create vulnerabilities and compliance gaps.' }, likelihood: 4, impact: 3, riskType: 'Compliance', mitigation: { ar: 'إنشاء سياسة اعتماد البرمجيات وأداة مراقبة مركزية', en: 'Create software approval policy and centralized monitoring tool' }, confidence: 0.85 },
    { riskName: { ar: 'هجمات برامج الفدية على البنية التحتية', en: 'Ransomware Attacks on Infrastructure' }, description: { ar: 'ضعف حماية نقاط النهاية وعدم تدريب الموظفين يزيد من احتمال إصابة الأنظمة ببرامج الفدية وتعطل العمليات.', en: 'Weak endpoint protection and insufficient employee training increase the probability of ransomware infection and operational disruption.' }, likelihood: 3, impact: 5, riskType: 'Cybersecurity', mitigation: { ar: 'تحديث أنظمة EDR وتنفيذ تدريبات محاكاة تصيد دورية', en: 'Update EDR systems and conduct regular phishing simulation drills' }, confidence: 0.90 },
    { riskName: { ar: 'تسرب بيانات حساسة عبر قنوات غير آمنة', en: 'Sensitive Data Leakage via Unsecured Channels' }, description: { ar: 'مشاركة بيانات العملاء والمعلومات السرية عبر البريد الإلكتروني الشخصي أو تطبيقات المراسلة دون تشفير.', en: 'Sharing customer data and confidential information via personal email or messaging apps without encryption.' }, likelihood: 4, impact: 4, riskType: 'Cybersecurity', mitigation: { ar: 'تفعيل نظام DLP وتشفير جميع قنوات الاتصال', en: 'Activate DLP system and encrypt all communication channels' }, confidence: 0.87 },
    { riskName: { ar: 'توقف الخدمات السحابية المزودة من أطراف ثالثة', en: 'Cloud Service Provider Outage' }, description: { ar: 'الاعتماد الكلي على مزود سحابي واحد دون خطة تبديل يخلق نقطة فشل منفردة لجميع الخدمات الرقمية.', en: 'Complete reliance on a single cloud provider without a failover plan creates a single point of failure for all digital services.' }, likelihood: 2, impact: 5, riskType: 'Operational', mitigation: { ar: 'وضع استراتيجية متعددة السحابات وخطط استمرارية خدمات', en: 'Develop multi-cloud strategy and service continuity plans' }, confidence: 0.82 },
    { riskName: { ar: 'عدم الامتثال لمعايير NCA للأمن السيبراني', en: 'Non-Compliance with NCA Cybersecurity Standards' }, description: { ar: 'التأخر في تطبيق ضوابط الأمن السيبراني المطلوبة من الهيئة الوطنية للأمن السيبراني يعرض المنظمة لعقوبات تنظيمية.', en: 'Delay in implementing cybersecurity controls required by NCA exposes the organization to regulatory penalties.' }, likelihood: 3, impact: 4, riskType: 'Compliance', mitigation: { ar: 'تشكيل فريق امتثال مخصص وجدول تنفيذ أسبوعي', en: 'Form dedicated compliance team with weekly implementation schedule' }, confidence: 0.91 },
    { riskName: { ar: 'نقص المهارات السيبرانية الحرجة', en: 'Critical Cybersecurity Skills Shortage' }, description: { ar: 'صعوبة استقطاب والاحتفاظ بالكفاءات المتخصصة في الأمن السيبراني يضعف قدرة الفريق على الاستجابة للحوادث.', en: 'Difficulty attracting and retaining specialized cybersecurity talent weakens the team\'s incident response capability.' }, likelihood: 4, impact: 3, riskType: 'Strategic', mitigation: { ar: 'برنامج تطوير مهني وشراكات مع أكاديميات الأمن السيبراني', en: 'Professional development program and partnerships with cybersecurity academies' }, confidence: 0.78 },
  ],
  Finance: [
    { riskName: { ar: 'أخطاء التقارير المالية', en: 'Financial Reporting Errors' }, description: { ar: 'إدخال البيانات يدوياً وعمليات التسوية تزيد من احتمال الأخطاء الجوهرية في التقارير المالية.', en: 'Manual data entry and reconciliation increase the probability of material misstatements in financial reports.' }, likelihood: 3, impact: 5, riskType: 'Financial', mitigation: { ar: 'أتمتة عمليات التسوية وتطبيق ضوابط مراجعة مزدوجة', en: 'Automate reconciliation processes and implement dual review controls' }, confidence: 0.91 },
    { riskName: { ar: 'مخاطر الاحتيال من عدم فصل المهام', en: 'Fraud Risk from Insufficient Segregation of Duties' }, description: { ar: 'تداخل المسؤوليات في معالجة المدفوعات يخلق فرصاً للاحتيال الداخلي أو المعاملات غير المصرح بها.', en: 'Overlapping responsibilities in payment processing create opportunities for internal fraud or unauthorized transactions.' }, likelihood: 3, impact: 4, riskType: 'Financial', mitigation: { ar: 'إعادة هيكلة الصلاحيات وفرض مبدأ الفصل بين المهام', en: 'Restructure permissions and enforce segregation of duties principle' }, confidence: 0.89 },
    { riskName: { ar: 'تعرض لتقلبات العملات الأجنبية', en: 'FX Exposure from Delayed Settlements' }, description: { ar: 'معالجة المعاملات عبر الحدود دون آليات تحوط فوري تعرض المنظمة لتقلبات أسعار الصرف.', en: 'Cross-border transaction processing without real-time hedging exposes the organization to FX rate fluctuations.' }, likelihood: 4, impact: 3, riskType: 'Financial', mitigation: { ar: 'تطبيق استراتيجية تحوط آلي وحدود تعرض يومية', en: 'Implement automated hedging strategy and daily exposure limits' }, confidence: 0.85 },
    { riskName: { ar: 'عدم الامتثال لمتطلبات ضريبة القيمة المضافة', en: 'VAT Compliance Failures' }, description: { ar: 'تعقيد الحسابات الضريبية وتغير اللوائح قد يؤدي لإقرارات ضريبية غير صحيحة وعقوبات من هيئة الزكاة.', en: 'Complex tax calculations and changing regulations may lead to incorrect VAT returns and ZATCA penalties.' }, likelihood: 3, impact: 4, riskType: 'Compliance', mitigation: { ar: 'تحديث النظام المحاسبي وتدريب الفريق على آخر التحديثات التنظيمية', en: 'Update accounting system and train team on latest regulatory changes' }, confidence: 0.88 },
    { riskName: { ar: 'تأخر إغلاق القوائم المالية', en: 'Delayed Financial Close' }, description: { ar: 'تعقيد العمليات المحاسبية والاعتماد على جداول البيانات يؤخر إغلاق الفترة المالية ويؤثر على اتخاذ القرار.', en: 'Complex accounting processes and spreadsheet dependency delay period close and impact decision-making.' }, likelihood: 4, impact: 3, riskType: 'Operational', mitigation: { ar: 'أتمتة عمليات الإغلاق وتطبيق نظام ERP متكامل', en: 'Automate close processes and implement integrated ERP system' }, confidence: 0.83 },
    { riskName: { ar: 'ضعف الرقابة الداخلية على المصروفات', en: 'Weak Internal Controls on Expenditures' }, description: { ar: 'عدم كفاية ضوابط الموافقة على المصروفات قد يؤدي لإنفاق غير مبرر أو تجاوز الميزانيات.', en: 'Inadequate expense approval controls may lead to unjustified spending or budget overruns.' }, likelihood: 3, impact: 3, riskType: 'Operational', mitigation: { ar: 'تعزيز مستويات الموافقة وتطبيق رقابة آلية على حدود الإنفاق', en: 'Strengthen approval levels and implement automated spending limit controls' }, confidence: 0.86 },
  ],
  Operations: [
    { riskName: { ar: 'نقطة فشل منفردة في سلسلة الإمداد', en: 'Supply Chain Single Point of Failure' }, description: { ar: 'الاعتماد المفرط على مزود لوجستيات واحد يخلق ثغرة أمام اضطرابات الخدمة أو الأحداث الجيوسياسية.', en: 'Over-reliance on a single logistics provider creates vulnerability to service disruptions or geopolitical events.' }, likelihood: 4, impact: 5, riskType: 'Operational', mitigation: { ar: 'تنويع قاعدة الموردين وإنشاء بدائل طوارئ', en: 'Diversify supplier base and establish emergency alternatives' }, confidence: 0.93 },
    { riskName: { ar: 'توقف المعدات بسبب تأجيل الصيانة', en: 'Equipment Downtime from Deferred Maintenance' }, description: { ar: 'الضغط التشغيلي للحفاظ على الإنتاج قد يؤدي لتأجيل الصيانة الوقائية وزيادة خطر الأعطال المفاجئة.', en: 'Operational pressure to maintain output may lead to postponed preventive maintenance and unexpected breakdowns.' }, likelihood: 3, impact: 4, riskType: 'Operational', mitigation: { ar: 'تطبيق نظام صيانة تنبؤي وجدول إلزامي للصيانة الدورية', en: 'Implement predictive maintenance system and mandatory periodic schedule' }, confidence: 0.87 },
    { riskName: { ar: 'مخاطر السلامة والصحة المهنية', en: 'Health & Safety Incident Risk' }, description: { ar: 'المهام اليدوية عالية التكرار وتشغيل المعدات دون مراقبة مستمرة تزيد احتمال الإصابات.', en: 'High-frequency manual tasks and equipment operation without continuous monitoring increase injury probability.' }, likelihood: 3, impact: 3, riskType: 'Compliance', mitigation: { ar: 'تعزيز برامج السلامة وتركيب أجهزة مراقبة ذكية', en: 'Enhance safety programs and install smart monitoring devices' }, confidence: 0.84 },
    { riskName: { ar: 'تأخر التسليم وتراكم الطلبات', en: 'Delivery Delays and Order Backlog' }, description: { ar: 'عدم كفاية القدرة الإنتاجية خلال فترات الذروة يؤدي لتأخر التسليم وفقدان رضا العملاء.', en: 'Insufficient production capacity during peak periods leads to delivery delays and customer dissatisfaction.' }, likelihood: 4, impact: 3, riskType: 'Operational', mitigation: { ar: 'تخطيط القدرة المسبق وإنشاء مخزون أمان استراتيجي', en: 'Advance capacity planning and establish strategic safety stock' }, confidence: 0.81 },
    { riskName: { ar: 'فشل أنظمة التحكم الصناعي (SCADA)', en: 'Industrial Control System (SCADA) Failure' }, description: { ar: 'تقادم أنظمة التحكم الصناعي وعدم تحديثها يخلق ثغرات أمنية ومخاطر توقف الإنتاج.', en: 'Aging industrial control systems without updates create security vulnerabilities and production stoppage risks.' }, likelihood: 3, impact: 5, riskType: 'Cybersecurity', mitigation: { ar: 'خطة تحديث مرحلي لأنظمة SCADA وفصل الشبكة الصناعية', en: 'Phased SCADA upgrade plan and industrial network segregation' }, confidence: 0.86 },
    { riskName: { ar: 'نقص العمالة المهرة في العمليات', en: 'Skilled Operations Labor Shortage' }, description: { ar: 'صعوبة استقطاب فنيين مؤهلين في بيئة تنافسية يؤثر على جودة التشغيل والإنتاجية.', en: 'Difficulty attracting qualified technicians in a competitive market impacts operational quality and productivity.' }, likelihood: 4, impact: 3, riskType: 'Strategic', mitigation: { ar: 'برامج التدريب الداخلي والشراكة مع المعاهد التقنية', en: 'Internal training programs and partnerships with technical institutes' }, confidence: 0.79 },
  ],
  HR: [
    { riskName: { ar: 'اعتماد حرج على الأفراد الرئيسيين', en: 'Key Personnel Dependency' }, description: { ar: 'تركز المعرفة المؤسسية في عدد قليل من الموظفين يخلق خطر استمرارية الأعمال عند مغادرتهم.', en: 'Critical knowledge concentrated in few employees creates business continuity risk if they leave.' }, likelihood: 4, impact: 4, riskType: 'Operational', mitigation: { ar: 'برنامج إدارة المعرفة وخطط التعاقب الوظيفي', en: 'Knowledge management program and succession planning' }, confidence: 0.90 },
    { riskName: { ar: 'انتهاك خصوصية بيانات الموظفين', en: 'Employee Data Privacy Breach' }, description: { ar: 'معالجة البيانات الشخصية الحساسة في عمليات الموارد البشرية دون تشفير وضوابط وصول كافية.', en: 'Handling sensitive personal data in HR processes without adequate encryption and access controls.' }, likelihood: 3, impact: 5, riskType: 'Compliance', mitigation: { ar: 'تشفير بيانات الموظفين وتطبيق سياسة الحد الأدنى من الوصول', en: 'Encrypt employee data and implement least-access policy' }, confidence: 0.91 },
    { riskName: { ar: 'أزمة الاحتفاظ بالمواهب', en: 'Talent Retention Crisis' }, description: { ar: 'فجوات في المقارنة المعيارية للرواتب ومحدودية مسارات التطور الوظيفي قد تؤدي لموجة استقالات.', en: 'Compensation benchmarking gaps and limited career pathways may trigger a wave of resignations.' }, likelihood: 4, impact: 3, riskType: 'Strategic', mitigation: { ar: 'مراجعة شاملة للرواتب وإنشاء مسارات مهنية واضحة', en: 'Comprehensive salary review and clear career path creation' }, confidence: 0.85 },
    { riskName: { ar: 'عدم الامتثال لنظام العمل السعودي', en: 'Saudi Labor Law Non-Compliance' }, description: { ar: 'التغييرات المتسارعة في نظام العمل ونسب التوطين قد تؤدي لعقوبات من وزارة الموارد البشرية.', en: 'Rapid changes in labor law and Saudization ratios may lead to Ministry of HR penalties.' }, likelihood: 3, impact: 4, riskType: 'Legal', mitigation: { ar: 'فريق متابعة تنظيمي ونظام إنذار مبكر للتغييرات القانونية', en: 'Regulatory monitoring team and early warning system for legal changes' }, confidence: 0.88 },
    { riskName: { ar: 'بيئة عمل سلبية ومخاطر التحرش', en: 'Hostile Work Environment and Harassment Risk' }, description: { ar: 'غياب آليات إبلاغ فعالة وعدم كفاية التدريب على السلوك المهني يخلق مخاطر قانونية وسمعية.', en: 'Lack of effective reporting mechanisms and insufficient professional conduct training create legal and reputational risks.' }, likelihood: 3, impact: 4, riskType: 'Reputational', mitigation: { ar: 'إنشاء قناة إبلاغ سرية وتدريب إلزامي على أخلاقيات العمل', en: 'Establish confidential reporting channel and mandatory workplace ethics training' }, confidence: 0.86 },
    { riskName: { ar: 'أخطاء الرواتب والمستحقات', en: 'Payroll and Benefits Errors' }, description: { ar: 'الحسابات اليدوية وتعقيد هيكل المكافآت يزيد احتمال أخطاء الرواتب وتأخر الدفع.', en: 'Manual calculations and complex reward structure increase probability of payroll errors and payment delays.' }, likelihood: 3, impact: 3, riskType: 'Operational', mitigation: { ar: 'أتمتة نظام الرواتب مع مراجعة مزدوجة قبل الصرف', en: 'Automate payroll system with dual review before disbursement' }, confidence: 0.84 },
  ],
  Legal: [
    { riskName: { ar: 'فجوة مراقبة الامتثال التعاقدي', en: 'Contract Compliance Monitoring Gap' }, description: { ar: 'حجم العقود النشطة يتجاوز القدرة الحالية للمراجعة، مما يخلق خطر تجاوز الالتزامات وبنود الغرامات.', en: 'Volume of active contracts exceeds review capacity, creating risk of missed obligations and penalty clauses.' }, likelihood: 4, impact: 4, riskType: 'Legal', mitigation: { ar: 'تطبيق نظام إدارة عقود آلي مع تنبيهات المواعيد', en: 'Implement automated contract management system with deadline alerts' }, confidence: 0.90 },
    { riskName: { ar: 'تأخر الاستجابة للتغييرات التنظيمية', en: 'Regulatory Change Response Delay' }, description: { ar: 'التطور السريع في المشهد التنظيمي قد يتجاوز قدرة الفريق القانوني على تحديث السياسات في الوقت المناسب.', en: 'Rapid regulatory landscape evolution may outpace the legal team ability to update policies timely.' }, likelihood: 3, impact: 5, riskType: 'Compliance', mitigation: { ar: 'اشتراك في خدمات التحديثات التنظيمية وتعيين مسؤول امتثال مخصص', en: 'Subscribe to regulatory update services and assign dedicated compliance officer' }, confidence: 0.92 },
    { riskName: { ar: 'مخاطر التقاضي من نزاعات الأطراف الثالثة', en: 'Litigation Exposure from Third-Party Disputes' }, description: { ar: 'تعقيد اتفاقيات الموردين والشركاء يخلق إمكانية النزاعات التعاقدية والتكاليف القانونية المرتبطة.', en: 'Complexity of vendor and partner agreements creates potential for contractual disputes and legal costs.' }, likelihood: 3, impact: 3, riskType: 'Legal', mitigation: { ar: 'مراجعة قانونية مسبقة لجميع العقود وإدراج شروط التحكيم', en: 'Pre-legal review of all contracts and inclusion of arbitration clauses' }, confidence: 0.83 },
    { riskName: { ar: 'انتهاك حقوق الملكية الفكرية', en: 'Intellectual Property Rights Violation' }, description: { ar: 'استخدام تقنيات أو محتوى دون تراخيص مناسبة يعرض المنظمة لدعاوى انتهاك الملكية الفكرية.', en: 'Using technologies or content without proper licenses exposes the organization to IP infringement lawsuits.' }, likelihood: 3, impact: 4, riskType: 'Legal', mitigation: { ar: 'جرد شامل للتراخيص وتطبيق سياسة استخدام الملكية الفكرية', en: 'Comprehensive license audit and IP usage policy implementation' }, confidence: 0.87 },
    { riskName: { ar: 'عدم الامتثال لنظام حماية البيانات الشخصية', en: 'Personal Data Protection Law Non-Compliance' }, description: { ar: 'عدم تطبيق متطلبات نظام حماية البيانات الشخصية (PDPL) يعرض المنظمة لعقوبات مالية كبيرة.', en: 'Failure to implement PDPL requirements exposes the organization to significant financial penalties.' }, likelihood: 4, impact: 4, riskType: 'Compliance', mitigation: { ar: 'تعيين مسؤول حماية بيانات (DPO) وتنفيذ تقييم تأثير الخصوصية', en: 'Appoint Data Protection Officer (DPO) and conduct privacy impact assessment' }, confidence: 0.93 },
    { riskName: { ar: 'مخاطر العقود الدولية والقانون المطبق', en: 'International Contract Jurisdiction Risk' }, description: { ar: 'العقود مع أطراف دولية دون تحديد واضح للاختصاص القضائي يخلق مخاطر في حالة النزاع.', en: 'Contracts with international parties without clear jurisdiction clauses create risks in case of disputes.' }, likelihood: 3, impact: 3, riskType: 'Legal', mitigation: { ar: 'توحيد شروط الاختصاص القضائي في جميع العقود الدولية', en: 'Standardize jurisdiction clauses in all international contracts' }, confidence: 0.81 },
  ],
  Compliance: [
    { riskName: { ar: 'فجوة الجاهزية للتدقيق', en: 'Audit Readiness Gap' }, description: { ar: 'قصور عمليات التوثيق وجمع الأدلة قد يؤدي لملاحظات تدقيق وعقوبات تنظيمية.', en: 'Insufficient documentation and evidence collection may result in audit findings and regulatory sanctions.' }, likelihood: 3, impact: 5, riskType: 'Compliance', mitigation: { ar: 'أتمتة جمع الأدلة وإنشاء مستودع مركزي للوثائق', en: 'Automate evidence collection and create centralized document repository' }, confidence: 0.92 },
    { riskName: { ar: 'انحراف السياسات عبر وحدات الأعمال', en: 'Policy Drift Across Business Units' }, description: { ar: 'التطبيق اللامركزي للسياسات أدى لممارسات امتثال غير متسقة عبر الإدارات.', en: 'Decentralized policy implementation has led to inconsistent compliance practices across departments.' }, likelihood: 4, impact: 4, riskType: 'Compliance', mitigation: { ar: 'مركزة إدارة السياسات وتنفيذ مراجعات ربعية', en: 'Centralize policy management and implement quarterly reviews' }, confidence: 0.88 },
    { riskName: { ar: 'ضعف ضوابط مكافحة غسل الأموال', en: 'Anti-Money Laundering Control Weakness' }, description: { ar: 'عتبات مراقبة المعاملات قد لا تكفي لرصد أنماط غسل الأموال الناشئة.', en: 'Transaction monitoring thresholds may not capture emerging money laundering typologies.' }, likelihood: 3, impact: 4, riskType: 'Compliance', mitigation: { ar: 'تحديث سيناريوهات المراقبة وتطبيق تحليلات AI متقدمة', en: 'Update monitoring scenarios and implement advanced AI analytics' }, confidence: 0.86 },
    { riskName: { ar: 'عدم الامتثال لمتطلبات الإفصاح', en: 'Disclosure Requirements Non-Compliance' }, description: { ar: 'تعقيد متطلبات الإفصاح التنظيمية المتعددة قد يؤدي لإغفال متطلبات إلزامية.', en: 'Complexity of multiple regulatory disclosure requirements may lead to missed mandatory requirements.' }, likelihood: 3, impact: 4, riskType: 'Legal', mitigation: { ar: 'إنشاء تقويم إفصاح مركزي ونظام تذكير آلي', en: 'Create centralized disclosure calendar and automated reminder system' }, confidence: 0.84 },
    { riskName: { ar: 'فشل برامج التدريب على الامتثال', en: 'Compliance Training Program Failure' }, description: { ar: 'عدم كفاية التدريب وانخفاض معدلات الإكمال يضعف الوعي بالامتثال ويزيد مخاطر المخالفات.', en: 'Insufficient training and low completion rates weaken compliance awareness and increase violation risks.' }, likelihood: 4, impact: 3, riskType: 'Operational', mitigation: { ar: 'تطبيق نظام تدريب إلكتروني إلزامي مع متابعة الإكمال', en: 'Implement mandatory e-learning system with completion tracking' }, confidence: 0.82 },
    { riskName: { ar: 'عدم تحديث سياسات الخصوصية', en: 'Outdated Privacy Policies' }, description: { ar: 'سياسات الخصوصية لا تعكس التغييرات في أنشطة معالجة البيانات أو التشريعات الجديدة.', en: 'Privacy policies do not reflect changes in data processing activities or new legislation.' }, likelihood: 3, impact: 3, riskType: 'Compliance', mitigation: { ar: 'مراجعة سنوية إلزامية لسياسات الخصوصية مع مشاركة الأطراف المعنية', en: 'Mandatory annual privacy policy review with stakeholder involvement' }, confidence: 0.80 },
  ],
};

// Default risks for unmapped departments
const defaultRisks = [
  { riskName: { ar: 'عدم كفاءة العمليات التشغيلية', en: 'Operational Process Inefficiency' }, description: { ar: 'تتضمن سير العمل الحالي خطوات مكررة وتسليمات يدوية تزيد من معدلات الخطأ.', en: 'Current workflows contain redundant steps and manual handoffs that increase error rates.' }, likelihood: 3, impact: 3, riskType: 'Operational', mitigation: { ar: 'تحسين العمليات وأتمتة الخطوات المتكررة', en: 'Process optimization and automation of repetitive steps' }, confidence: 0.75 },
  { riskName: { ar: 'فجوة أمن المعلومات', en: 'Information Security Gap' }, description: { ar: 'التعامل اليومي مع البيانات الحساسة دون بروتوكولات أمان شاملة يخلق ناقلات تعرض محتملة.', en: 'Daily sensitive data handling without comprehensive security protocols creates exposure vectors.' }, likelihood: 4, impact: 4, riskType: 'Cybersecurity', mitigation: { ar: 'تطبيق ضوابط أمن معلومات شاملة', en: 'Implement comprehensive information security controls' }, confidence: 0.78 },
  { riskName: { ar: 'ثغرة استمرارية الأعمال', en: 'Business Continuity Vulnerability' }, description: { ar: 'عدم وجود خطط طوارئ موثقة للعمليات اليومية الحرجة يخلق هشاشة مؤسسية.', en: 'Lack of documented contingency plans for critical operations creates organizational vulnerability.' }, likelihood: 3, impact: 4, riskType: 'Operational', mitigation: { ar: 'وضع وتوثيق خطط استمرارية الأعمال', en: 'Develop and document business continuity plans' }, confidence: 0.76 },
  { riskName: { ar: 'مخاطر الامتثال التنظيمي', en: 'Regulatory Compliance Risk' }, description: { ar: 'تغير اللوائح والأنظمة دون تحديث كاف للسياسات والإجراءات الداخلية.', en: 'Changing regulations without adequate updates to internal policies and procedures.' }, likelihood: 3, impact: 4, riskType: 'Compliance', mitigation: { ar: 'مراقبة تنظيمية مستمرة وتحديث دوري للسياسات', en: 'Continuous regulatory monitoring and periodic policy updates' }, confidence: 0.80 },
  { riskName: { ar: 'فقدان المعرفة المؤسسية', en: 'Institutional Knowledge Loss' }, description: { ar: 'عدم توثيق العمليات والإجراءات يعرض المنظمة لفقدان المعرفة عند مغادرة الموظفين.', en: 'Lack of process documentation exposes the organization to knowledge loss when employees leave.' }, likelihood: 4, impact: 3, riskType: 'Strategic', mitigation: { ar: 'برنامج إدارة المعرفة والتوثيق المنهجي', en: 'Knowledge management program and systematic documentation' }, confidence: 0.82 },
  { riskName: { ar: 'مخاطر السمعة المؤسسية', en: 'Corporate Reputation Risk' }, description: { ar: 'ضعف إدارة التواصل في الأزمات وغياب مراقبة وسائل التواصل الاجتماعي.', en: 'Weak crisis communication management and lack of social media monitoring.' }, likelihood: 3, impact: 4, riskType: 'Reputational', mitigation: { ar: 'وضع خطة اتصالات الأزمات ومراقبة السمعة الرقمية', en: 'Develop crisis communications plan and digital reputation monitoring' }, confidence: 0.77 },
];

/**
 * Simulates AI-powered risk generation with department-specific persona.
 * Returns 6-8 bilingual risks per department.
 */
export async function generateRisksWithAI(tasks, department, language = 'en') {
  // Simulate 3-second AI processing
  await new Promise(r => setTimeout(r, 3000));

  const deptMap = {
    'IT': 'IT', 'تقنية المعلومات': 'IT',
    'Finance': 'Finance', 'المالية': 'Finance',
    'Operations': 'Operations', 'العمليات': 'Operations',
    'HR': 'HR', 'الموارد البشرية': 'HR',
    'Legal': 'Legal', 'الشؤون القانونية': 'Legal',
    'Compliance': 'Compliance', 'الامتثال': 'Compliance',
    'Marketing': 'Operations', 'التسويق': 'Operations',
    'Strategy': 'Operations', 'الاستراتيجية': 'Operations',
    'Procurement': 'Operations', 'المشتريات': 'Operations',
  };

  const key = deptMap[department] || null;
  const templates = key ? riskTemplates[key] : defaultRisks;

  // Return risks with localized names
  return templates.map((r, i) => ({
    riskName: typeof r.riskName === 'object' ? r.riskName[language] || r.riskName.en : r.riskName,
    description: typeof r.description === 'object' ? r.description[language] || r.description.en : r.description,
    likelihood: r.likelihood,
    impact: r.impact,
    riskType: r.riskType,
    mitigation: typeof r.mitigation === 'object' ? r.mitigation[language] || r.mitigation.en : (r.mitigation || ''),
    confidence: r.confidence || 0.8,
    tempId: `AI-${Date.now()}-${i}`,
    selected: false,
  }));
}
